global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'finance-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'purchase-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'sales-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'hr-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'production-service'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s