server:
  port: 8101

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_main
    username: erp_user
    password: erp_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 3600000  # 1 hour
    refresh-expiration: 86400000  # 24 hours

logging:
  level:
    com.erp.system.user: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always